# Netlify configuration for Unity WebGL Gzip compressed builds
[[headers]]
  for = "/Build/*.data.gz"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.wasm.gz"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.js.gz"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.symbols.json.gz"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "gzip"
